"""Deterministic GSO choice, with the geometry the HOST needs.

Regenerate with `bash docker/kubric.sh scripts/refresh_gso_ids.py --write`.

The manifest lives in the container, but scenario sampling runs on the host --
where a body stands, how far a distractor must clear it and what its support
surface is are all decided before anything is rendered. An environment map has
no geometry so `_hdri.py` bakes ids alone; a GSO object does, so this bakes its
BOUNDS as well.

Curated: squat and roughly isotropic (longest axis at most 3.2 x the
shortest). A physics dataset needs bodies whose lawful motion a viewer can
predict -- something that topples unexpectedly reads as the violation.

`held_out` marks the assets in Kubric's own 10% test split, kept so a release
can align its held-out clips with objects the community also treats as unseen.
`license` is carried because non-negotiable 7 requires every asset to ship one,
and `validate` enforces it -- recorded when the source is enabled, not at
release.
"""
from __future__ import annotations

from typing import Dict, List

GSO_ASSETS: Dict[str, dict] = {   '3D_Dollhouse_Swing': {   'bounds': [   [-0.05241, -0.057424, -0.026756],
                                            [0.052409, 0.037832, 0.06539]],
                              'category': 'Toys',
                              'held_out': False,
                              'license': 'CC BY-SA 4.0'},
    'Asus_Z97IPLUS_Motherboard_Mini_ITX_LGA1150_Socket': {   'bounds': [   [   -0.115548,
                                                                               -0.049728,
                                                                               -0.094689],
                                                                           [   0.115988,
                                                                               0.049978,
                                                                               0.094921]],
                                                             'category': 'None',
                                                             'held_out': False,
                                                             'license': 'CC '
                                                                        'BY-SA '
                                                                        '4.0'},
    'BIA_Cordon_Bleu_White_Porcelain_Utensil_Holder_900028': {   'bounds': [   [   -0.074464,
                                                                                   -0.073795,
                                                                                   -0.073534],
                                                                               [   0.073106,
                                                                                   0.07496,
                                                                                   0.101661]],
                                                                 'category': 'None',
                                                                 'held_out': False,
                                                                 'license': 'CC '
                                                                            'BY-SA '
                                                                            '4.0'},
    'BIA_Porcelain_Ramekin_With_Glazed_Rim_35_45_oz_cup': {   'bounds': [   [   -0.044513,
                                                                                -0.044275,
                                                                                -0.016904],
                                                                            [   0.044166,
                                                                                0.044378,
                                                                                0.026426]],
                                                              'category': 'None',
                                                              'held_out': False,
                                                              'license': 'CC '
                                                                         'BY-SA '
                                                                         '4.0'},
    'BlackBlack_Nintendo_3DSXL': {   'bounds': [   [   -0.077625,
                                                       -0.0679,
                                                       -0.021969],
                                                   [   0.077915,
                                                       0.068893,
                                                       0.068554]],
                                     'category': 'None',
                                     'held_out': False,
                                     'license': 'CC BY-SA 4.0'},
    'Black_Decker_CM2035B_12Cup_Thermal_Coffeemaker': {   'bounds': [   [   -0.115312,
                                                                            -0.127929,
                                                                            -0.167789],
                                                                        [   0.111623,
                                                                            0.1957,
                                                                            0.169148]],
                                                          'category': 'None',
                                                          'held_out': False,
                                                          'license': 'CC '
                                                                     'BY-SA '
                                                                     '4.0'},
    'Black_Decker_Stainless_Steel_Toaster_4_Slice': {   'bounds': [   [   -0.139605,
                                                                          -0.151781,
                                                                          -0.090532],
                                                                      [   0.148206,
                                                                          0.166518,
                                                                          0.098337]],
                                                        'category': 'None',
                                                        'held_out': True,
                                                        'license': 'CC BY-SA '
                                                                   '4.0'},
    'Black_and_Decker_TR3500SD_2Slice_Toaster': {   'bounds': [   [   -0.082649,
                                                                      -0.134981,
                                                                      -0.089269],
                                                                  [   0.085136,
                                                                      0.160296,
                                                                      0.10145]],
                                                    'category': 'None',
                                                    'held_out': False,
                                                    'license': 'CC BY-SA '
                                                               '4.0'},
    'BlueBlack_Nintendo_3DSXL': {   'bounds': [   [   -0.078221,
                                                      -0.066624,
                                                      -0.022236],
                                                  [   0.078378,
                                                      0.067038,
                                                      0.070419]],
                                    'category': 'None',
                                    'held_out': False,
                                    'license': 'CC BY-SA 4.0'},
    'Bradshaw_International_11642_7_Qt_MP_Plastic_Bowl': {   'bounds': [   [   -0.142866,
                                                                               -0.141254,
                                                                               -0.079294],
                                                                           [   0.139748,
                                                                               0.143836,
                                                                               0.07521]],
                                                             'category': 'None',
                                                             'held_out': True,
                                                             'license': 'CC '
                                                                        'BY-SA '
                                                                        '4.0'},
    'CHICKEN_RACER': {   'bounds': [   [-0.045869, -0.045446, -0.028911],
                                       [0.045802, 0.042521, 0.070546]],
                         'category': 'Toys',
                         'held_out': False,
                         'license': 'CC BY-SA 4.0'},
    'Calphalon_Kitchen_Essentials_12_Cast_Iron_Fry_Pan_Black': {   'bounds': [   [   -0.158762,
                                                                                     -0.158482,
                                                                                     -0.073841],
                                                                                 [   0.163593,
                                                                                     0.165146,
                                                                                     0.072398]],
                                                                   'category': 'None',
                                                                   'held_out': False,
                                                                   'license': 'CC '
                                                                              'BY-SA '
                                                                              '4.0'},
    'Closetmaid_Premium_Fabric_Cube_Red': {   'bounds': [   [   -0.175478,
                                                                -0.143088,
                                                                -0.073495],
                                                            [   0.146192,
                                                                0.131877,
                                                                0.21566]],
                                              'category': 'None',
                                              'held_out': False,
                                              'license': 'CC BY-SA 4.0'},
    'Cole_Hardware_Antislip_Surfacing_Material_White': {   'bounds': [   [   -0.07718,
                                                                             -0.076987,
                                                                             -0.054191],
                                                                         [   0.077699,
                                                                             0.077343,
                                                                             0.053583]],
                                                           'category': 'None',
                                                           'held_out': False,
                                                           'license': 'CC '
                                                                      'BY-SA '
                                                                      '4.0'},
    'Cole_Hardware_Electric_Pot_Assortment_55': {   'bounds': [   [   -0.071911,
                                                                      -0.071049,
                                                                      -0.063868],
                                                                  [   0.071073,
                                                                      0.069522,
                                                                      0.064117]],
                                                    'category': 'None',
                                                    'held_out': True,
                                                    'license': 'CC BY-SA '
                                                               '4.0'},
    'Cole_Hardware_Electric_Pot_Cabana_55': {   'bounds': [   [   -0.070876,
                                                                  -0.070768,
                                                                  -0.066465],
                                                              [   0.070792,
                                                                  0.071166,
                                                                  0.063591]],
                                                'category': 'None',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'Cole_Hardware_Flower_Pot_1025': {   'bounds': [   [   -0.126971,
                                                           -0.12435,
                                                           -0.114822],
                                                       [   0.122891,
                                                           0.122372,
                                                           0.101983]],
                                         'category': 'None',
                                         'held_out': False,
                                         'license': 'CC BY-SA 4.0'},
    'Cole_Hardware_Mug_Classic_Blue': {   'bounds': [   [   -0.070182,
                                                            -0.063381,
                                                            -0.045884],
                                                        [   0.09548,
                                                            0.062159,
                                                            0.048885]],
                                          'category': 'None',
                                          'held_out': False,
                                          'license': 'CC BY-SA 4.0'},
    'Cole_Hardware_Orchid_Pot_85': {   'bounds': [   [   -0.106783,
                                                         -0.105426,
                                                         -0.07078],
                                                     [   0.10465,
                                                         0.104763,
                                                         0.077265]],
                                       'category': 'None',
                                       'held_out': False,
                                       'license': 'CC BY-SA 4.0'},
    'Crayola_Washable_Fingerpaint_Red_Blue_Yellow_3_count_8_fl_oz_bottes_each': {   'bounds': [   [   -0.088616,
                                                                                                      -0.0349,
                                                                                                      -0.074512],
                                                                                                  [   0.088421,
                                                                                                      0.030035,
                                                                                                      0.073186]],
                                                                                    'category': 'None',
                                                                                    'held_out': False,
                                                                                    'license': 'CC '
                                                                                               'BY-SA '
                                                                                               '4.0'},
    'Creatine_Monohydrate': {   'bounds': [   [   -0.064329,
                                                  -0.064319,
                                                  -0.089383],
                                              [0.064409, 0.064343, 0.094431]],
                                'category': 'Bottles and Cans and Cups',
                                'held_out': False,
                                'license': 'CC BY-SA 4.0'},
    'Curver_Storage_Bin_Black_Small': {   'bounds': [   [   -0.143571,
                                                            -0.096577,
                                                            -0.056336],
                                                        [   0.142293,
                                                            0.096685,
                                                            0.077682]],
                                          'category': 'None',
                                          'held_out': False,
                                          'license': 'CC BY-SA 4.0'},
    'DPC_Handmade_Hat_Brown': {   'bounds': [   [   -0.153851,
                                                    -0.176246,
                                                    -0.075534],
                                                [   0.16453,
                                                    0.177657,
                                                    0.067656]],
                                  'category': 'Hat',
                                  'held_out': False,
                                  'license': 'CC BY-SA 4.0'},
    'DPC_tropical_Trends_Hat': {   'bounds': [   [   -0.19135,
                                                     -0.199347,
                                                     -0.100244],
                                                 [   0.185016,
                                                     0.204509,
                                                     0.071574]],
                                   'category': 'Hat',
                                   'held_out': False,
                                   'license': 'CC BY-SA 4.0'},
    'Dixie_10_ounce_Bowls_35_ct': {   'bounds': [   [   -0.076146,
                                                        -0.076784,
                                                        -0.036584],
                                                    [   0.076023,
                                                        0.075299,
                                                        0.042817]],
                                      'category': 'None',
                                      'held_out': False,
                                      'license': 'CC BY-SA 4.0'},
    'Dog': {   'bounds': [   [-0.114771, -0.081997, -0.080322],
                             [0.11722, 0.104137, 0.118939]],
               'category': 'None',
               'held_out': False,
               'license': 'CC BY-SA 4.0'},
    'Don_Franciscos_Gourmet_Coffee_Medium_Decaf_100_Colombian_12_oz_340_g': {   'bounds': [   [   -0.051095,
                                                                                                  -0.051846,
                                                                                                  -0.071229],
                                                                                              [   0.051969,
                                                                                                  0.051277,
                                                                                                  0.069812]],
                                                                                'category': 'Bottles '
                                                                                            'and '
                                                                                            'Cans '
                                                                                            'and '
                                                                                            'Cups',
                                                                                'held_out': False,
                                                                                'license': 'CC '
                                                                                           'BY-SA '
                                                                                           '4.0'},
    'Down_To_Earth_Ceramic_Orchid_Pot_Asst_Blue': {   'bounds': [   [   -0.067614,
                                                                        -0.066504,
                                                                        -0.048243],
                                                                    [   0.065111,
                                                                        0.06623,
                                                                        0.071089]],
                                                      'category': 'None',
                                                      'held_out': True,
                                                      'license': 'CC BY-SA '
                                                                 '4.0'},
    'Down_To_Earth_Orchid_Pot_Ceramic_Lime': {   'bounds': [   [   -0.069036,
                                                                   -0.069425,
                                                                   -0.048641],
                                                               [   0.071062,
                                                                   0.069979,
                                                                   0.078488]],
                                                 'category': 'Consumer Goods',
                                                 'held_out': False,
                                                 'license': 'CC BY-SA 4.0'},
    'Down_To_Earth_Orchid_Pot_Ceramic_Red': {   'bounds': [   [   -0.064047,
                                                                  -0.066662,
                                                                  -0.04579],
                                                              [   0.066521,
                                                                  0.064697,
                                                                  0.074075]],
                                                'category': 'Consumer Goods',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'ENFR_MID_ENFORCER': {   'bounds': [   [-0.062281, -0.175034, -0.053678],
                                           [0.061623, 0.118044, 0.109317]],
                             'category': 'Shoe',
                             'held_out': False,
                             'license': 'CC BY-SA 4.0'},
    'Ecoforms_Garden_Pot_GP16ATurquois': {   'bounds': [   [   -0.084766,
                                                               -0.083314,
                                                               -0.08379],
                                                           [   0.079502,
                                                               0.08065,
                                                               0.07727]],
                                             'category': 'None',
                                             'held_out': False,
                                             'license': 'CC BY-SA 4.0'},
    'Ecoforms_Plant_Container_12_Pot_Nova': {   'bounds': [   [   -0.150393,
                                                                  -0.139212,
                                                                  -0.151048],
                                                              [   0.146679,
                                                                  0.158162,
                                                                  0.135801]],
                                                'category': 'None',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'Ecoforms_Plant_Container_GP16AMOCHA': {   'bounds': [   [   -0.082398,
                                                                 -0.082324,
                                                                 -0.077469],
                                                             [   0.080313,
                                                                 0.07925,
                                                                 0.083819]],
                                               'category': 'None',
                                               'held_out': False,
                                               'license': 'CC BY-SA 4.0'},
    'Ecoforms_Plant_Container_GP16A_Coral': {   'bounds': [   [   -0.080881,
                                                                  -0.084185,
                                                                  -0.07906],
                                                              [   0.083861,
                                                                  0.080283,
                                                                  0.081775]],
                                                'category': 'None',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'Ecoforms_Plant_Container_QP_Harvest': {   'bounds': [   [   -0.043807,
                                                                 -0.043213,
                                                                 -0.049661],
                                                             [   0.044162,
                                                                 0.04418,
                                                                 0.040328]],
                                               'category': 'None',
                                               'held_out': False,
                                               'license': 'CC BY-SA 4.0'},
    'Ecoforms_Plant_Container_QP_Turquoise': {   'bounds': [   [   -0.04517,
                                                                   -0.043894,
                                                                   -0.049061],
                                                               [   0.04276,
                                                                   0.044278,
                                                                   0.040751]],
                                                 'category': 'None',
                                                 'held_out': False,
                                                 'license': 'CC BY-SA 4.0'},
    'Ecoforms_Plant_Container_URN_NAT': {   'bounds': [   [   -0.07107,
                                                              -0.075595,
                                                              -0.087288],
                                                          [   0.077796,
                                                              0.073274,
                                                              0.072644]],
                                            'category': 'Consumer Goods',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Ecoforms_Plant_Container_URN_SAN': {   'bounds': [   [   -0.069785,
                                                              -0.071683,
                                                              -0.086477],
                                                          [   0.079394,
                                                              0.077007,
                                                              0.072882]],
                                            'category': 'Consumer Goods',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Elephant': {   'bounds': [   [-0.094318, -0.110356, -0.095586],
                                  [0.097111, 0.099539, 0.174962]],
                    'category': 'None',
                    'held_out': False,
                    'license': 'CC BY-SA 4.0'},
    'Embark_Lunch_Cooler_Blue': {   'bounds': [   [   -0.159324,
                                                      -0.099713,
                                                      -0.084798],
                                                  [   0.13625,
                                                      0.101089,
                                                      0.110758]],
                                    'category': 'None',
                                    'held_out': False,
                                    'license': 'CC BY-SA 4.0'},
    'FAIRY_TALE_BLOCKS': {   'bounds': [   [-0.1271, -0.14853, -0.071732],
                                           [0.120589, 0.116509, 0.151371]],
                             'category': 'Toys',
                             'held_out': False,
                             'license': 'CC BY-SA 4.0'},
    'Fisher_price_Classic_Toys_Buzzy_Bee': {   'bounds': [   [   -0.077759,
                                                                 -0.068605,
                                                                 -0.042748],
                                                             [   0.128144,
                                                                 0.066181,
                                                                 0.069175]],
                                               'category': 'None',
                                               'held_out': False,
                                               'license': 'CC BY-SA 4.0'},
    'Fujifilm_instax_SHARE_SP1_10_photos': {   'bounds': [   [   -0.051263,
                                                                 -0.021571,
                                                                 -0.058855],
                                                             [   0.05168,
                                                                 0.021396,
                                                                 0.064878]],
                                               'category': 'None',
                                               'held_out': False,
                                               'license': 'CC BY-SA 4.0'},
    'Full_Circle_Happy_Scraps_Out_Collector_Gray': {   'bounds': [   [   -0.108486,
                                                                         -0.06619,
                                                                         -0.071871],
                                                                     [   0.10456,
                                                                         0.088862,
                                                                         0.071221]],
                                                       'category': 'None',
                                                       'held_out': False,
                                                       'license': 'CC BY-SA '
                                                                  '4.0'},
    'Granimals_20_Wooden_ABC_Blocks_Wagon_85VdSftGsLi': {   'bounds': [   [   -0.015377,
                                                                              -0.015578,
                                                                              -0.015277],
                                                                          [   0.015249,
                                                                              0.015611,
                                                                              0.015186]],
                                                            'category': 'None',
                                                            'held_out': False,
                                                            'license': 'CC '
                                                                       'BY-SA '
                                                                       '4.0'},
    'Great_Dinos_Triceratops_Toy': {   'bounds': [   [   -0.034738,
                                                         -0.022628,
                                                         -0.039786],
                                                     [   0.034733,
                                                         0.023179,
                                                         0.039398]],
                                       'category': 'None',
                                       'held_out': False,
                                       'license': 'CC BY-SA 4.0'},
    'Guardians_of_the_Galaxy_Galactic_Battlers_Rocket_Raccoon_Figure': {   'bounds': [   [   -0.030125,
                                                                                             -0.06084,
                                                                                             -0.057973],
                                                                                         [   0.022935,
                                                                                             0.040603,
                                                                                             0.040159]],
                                                                           'category': 'Action '
                                                                                       'Figures',
                                                                           'held_out': False,
                                                                           'license': 'CC '
                                                                                      'BY-SA '
                                                                                      '4.0'},
    'HeavyDuty_Flashlight': {   'bounds': [   [   -0.043458,
                                                  -0.04448,
                                                  -0.122792],
                                              [0.034139, 0.033405, 0.106413]],
                                'category': 'None',
                                'held_out': False,
                                'license': 'CC BY-SA 4.0'},
    'Hefty_Waste_Basket_Decorative_Bronze_85_liter': {   'bounds': [   [   -0.139633,
                                                                           -0.100545,
                                                                           -0.075485],
                                                                       [   0.131053,
                                                                           0.103624,
                                                                           0.224732]],
                                                         'category': 'None',
                                                         'held_out': False,
                                                         'license': 'CC '
                                                                    'BY-SA '
                                                                    '4.0'},
    'HyperX_Cloud_II_Headset_Gun_Metal': {   'bounds': [   [   -0.122681,
                                                               -0.063107,
                                                               -0.149283],
                                                           [   0.12256,
                                                               0.064154,
                                                               0.180261]],
                                             'category': 'Headphones',
                                             'held_out': True,
                                             'license': 'CC BY-SA 4.0'},
    'HyperX_Cloud_II_Headset_Red': {   'bounds': [   [   -0.12361,
                                                         -0.062029,
                                                         -0.149014],
                                                     [   0.122613,
                                                         0.062234,
                                                         0.182266]],
                                       'category': 'Headphones',
                                       'held_out': False,
                                       'license': 'CC BY-SA 4.0'},
    'INTERNATIONAL_PAPER_Willamette_4_Brown_Bag_500Count': {   'bounds': [   [   -0.133857,
                                                                                 -0.129567,
                                                                                 -0.069263],
                                                                             [   0.136218,
                                                                                 0.127857,
                                                                                 0.070458]],
                                                               'category': 'None',
                                                               'held_out': False,
                                                               'license': 'CC '
                                                                          'BY-SA '
                                                                          '4.0'},
    'Imaginext_Castle_Ogre': {   'bounds': [   [   -0.203829,
                                                   -0.098292,
                                                   -0.127126],
                                               [   0.191826,
                                                   0.095828,
                                                   0.110082]],
                                 'category': 'Action Figures',
                                 'held_out': False,
                                 'license': 'CC BY-SA 4.0'},
    'InterDesign_Over_Door': {   'bounds': [   [   -0.107741,
                                                   -0.094094,
                                                   -0.039032],
                                               [0.10742, 0.197147, 0.057971]],
                                 'category': 'None',
                                 'held_out': False,
                                 'license': 'CC BY-SA 4.0'},
    'IsoRich_Soy': {   'bounds': [   [-0.06117, -0.061019, -0.082084],
                                     [0.061209, 0.060961, 0.086755]],
                       'category': 'Bottles and Cans and Cups',
                       'held_out': True,
                       'license': 'CC BY-SA 4.0'},
    'JA_Henckels_International_Premio_Cutlery_Block_Set_14Piece': {   'bounds': [   [   -0.057253,
                                                                                        -0.183236,
                                                                                        -0.097522],
                                                                                    [   0.055469,
                                                                                        0.169088,
                                                                                        0.211766]],
                                                                      'category': 'None',
                                                                      'held_out': False,
                                                                      'license': 'CC '
                                                                                 'BY-SA '
                                                                                 '4.0'},
    'Jansport_School_Backpack_Blue_Streak': {   'bounds': [   [   -0.16724,
                                                                  -0.200038,
                                                                  -0.200601],
                                                              [   0.190416,
                                                                  0.169308,
                                                                  0.239547]],
                                                'category': 'Bag',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'KITCHEN_SET_CLASSIC_40HwCHfeG0H': {   'bounds': [   [   -0.113872,
                                                             -0.119032,
                                                             -0.046435],
                                                         [   0.071563,
                                                             0.048269,
                                                             0.104859]],
                                           'category': 'Toys',
                                           'held_out': True,
                                           'license': 'CC BY-SA 4.0'},
    'KS_Chocolate_Cube_Box_Assortment_By_Neuhaus_2010_Ounces': {   'bounds': [   [   -0.079103,
                                                                                     -0.105448,
                                                                                     -0.078004],
                                                                                 [   0.09112,
                                                                                     0.079026,
                                                                                     0.094253]],
                                                                   'category': 'Consumer '
                                                                               'Goods',
                                                                   'held_out': False,
                                                                   'license': 'CC '
                                                                              'BY-SA '
                                                                              '4.0'},
    'LEGO_5887_Dino_Defense_HQ': {   'bounds': [   [   -0.231135,
                                                       -0.179919,
                                                       -0.076976],
                                                   [   0.220582,
                                                       0.167422,
                                                       0.184734]],
                                     'category': 'Legos',
                                     'held_out': False,
                                     'license': 'CC BY-SA 4.0'},
    'LEGO_Bricks_More_Creative_Suitcase': {   'bounds': [   [   -0.190061,
                                                                -0.073098,
                                                                -0.141621],
                                                            [   0.191035,
                                                                0.07395,
                                                                0.142185]],
                                              'category': 'Legos',
                                              'held_out': False,
                                              'license': 'CC BY-SA 4.0'},
    'LEGO_Duplo_Build_and_Play_Box_4629': {   'bounds': [   [   -0.221292,
                                                                -0.138991,
                                                                -0.072365],
                                                            [   0.218342,
                                                                0.104912,
                                                                0.144669]],
                                              'category': 'Legos',
                                              'held_out': False,
                                              'license': 'CC BY-SA 4.0'},
    'LEGO_Duplo_Creative_Animals_10573': {   'bounds': [   [   -0.193859,
                                                               -0.063573,
                                                               -0.051094],
                                                           [   0.195365,
                                                               0.084888,
                                                               0.108628]],
                                             'category': 'Legos',
                                             'held_out': False,
                                             'license': 'CC BY-SA 4.0'},
    'Lego_Friends_Mia': {   'bounds': [   [-0.044626, -0.103882, -0.018206],
                                          [0.046859, 0.095002, 0.055815]],
                            'category': 'Legos',
                            'held_out': False,
                            'license': 'CC BY-SA 4.0'},
    'Lenovo_Yoga_2_11': {   'bounds': [   [-0.150025, -0.137243, -0.028198],
                                          [0.149527, 0.182678, 0.157209]],
                            'category': 'None',
                            'held_out': False,
                            'license': 'CC BY-SA 4.0'},
    'Logitech_Ultimate_Ears_Boom_Wireless_Speaker_Night_Black': {   'bounds': [   [   -0.053209,
                                                                                      -0.051188,
                                                                                      -0.127245],
                                                                                  [   0.052636,
                                                                                      0.052814,
                                                                                      0.133421]],
                                                                    'category': 'None',
                                                                    'held_out': False,
                                                                    'license': 'CC '
                                                                               'BY-SA '
                                                                               '4.0'},
    'Lovable_Huggable_Cuddly_Boutique_Teddy_Bear_Beige': {   'bounds': [   [   -0.124127,
                                                                               -0.201058,
                                                                               -0.050043],
                                                                           [   0.144578,
                                                                               0.169554,
                                                                               0.073687]],
                                                             'category': 'Stuffed '
                                                                         'Toys',
                                                             'held_out': False,
                                                             'license': 'CC '
                                                                        'BY-SA '
                                                                        '4.0'},
    'Mad_Gab_Refresh_Card_Game': {   'bounds': [   [   -0.078074,
                                                       -0.077978,
                                                       -0.078223],
                                                   [   0.077792,
                                                       0.078026,
                                                       0.077682]],
                                     'category': 'Board Games',
                                     'held_out': False,
                                     'license': 'CC BY-SA 4.0'},
    'Markings_Desk_Caddy': {   'bounds': [   [   -0.056551,
                                                 -0.137029,
                                                 -0.037004],
                                             [0.048648, 0.156315, 0.075935]],
                               'category': 'None',
                               'held_out': False,
                               'license': 'CC BY-SA 4.0'},
    'Markings_Letter_Holder': {   'bounds': [   [   -0.046185,
                                                    -0.098285,
                                                    -0.037716],
                                                [   0.053572,
                                                    0.100088,
                                                    0.103278]],
                                  'category': 'None',
                                  'held_out': False,
                                  'license': 'CC BY-SA 4.0'},
    'Mist_Wipe_Warmer': {   'bounds': [   [-0.132034, -0.061567, -0.116525],
                                          [0.132157, 0.066168, 0.116591]],
                            'category': 'None',
                            'held_out': False,
                            'license': 'CC BY-SA 4.0'},
    'My_Little_Pony_Princess_Celestia': {   'bounds': [   [   -0.09279,
                                                              -0.094826,
                                                              -0.113328],
                                                          [   0.100387,
                                                              0.129109,
                                                              0.118649]],
                                            'category': 'Toys',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Neat_Solutions_Character_Bib_2_pack': {   'bounds': [   [   -0.103273,
                                                                 -0.101042,
                                                                 -0.029254],
                                                             [   0.101882,
                                                                 0.103823,
                                                                 0.047319]],
                                               'category': 'None',
                                               'held_out': False,
                                               'license': 'CC BY-SA 4.0'},
    'Nescafe_16Count_Dolce_Gusto_Cappuccino_Capsules': {   'bounds': [   [   -0.062041,
                                                                             -0.062206,
                                                                             -0.060542],
                                                                         [   0.061741,
                                                                             0.061766,
                                                                             0.062052]],
                                                           'category': 'Consumer '
                                                                       'Goods',
                                                           'held_out': False,
                                                           'license': 'CC '
                                                                      'BY-SA '
                                                                      '4.0'},
    'Nickelodeon_Teenage_Mutant_Ninja_Turtles_Leonardo': {   'bounds': [   [   -0.054513,
                                                                               -0.078888,
                                                                               -0.058258],
                                                                           [   0.029884,
                                                                               0.038389,
                                                                               0.055456]],
                                                             'category': 'Action '
                                                                         'Figures',
                                                             'held_out': False,
                                                             'license': 'CC '
                                                                        'BY-SA '
                                                                        '4.0'},
    'Nickelodeon_Teenage_Mutant_Ninja_Turtles_Raphael': {   'bounds': [   [   -0.045797,
                                                                              -0.039391,
                                                                              -0.058228],
                                                                          [   0.0512,
                                                                              0.025838,
                                                                              0.071334]],
                                                            'category': 'Action '
                                                                        'Figures',
                                                            'held_out': False,
                                                            'license': 'CC '
                                                                       'BY-SA '
                                                                       '4.0'},
    'Nikon_1_AW1_w11275mm_Lens_Silver': {   'bounds': [   [   -0.031325,
                                                              -0.031421,
                                                              -0.038961],
                                                          [   0.031505,
                                                              0.031434,
                                                              0.039671]],
                                            'category': 'Camera',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Nintendo_Wii_Party_U_with_Controller_Wii_U_Game': {   'bounds': [   [   -0.072813,
                                                                             -0.031827,
                                                                             -0.098441],
                                                                         [   0.072607,
                                                                             0.031525,
                                                                             0.098671]],
                                                           'category': 'Media '
                                                                       'Cases',
                                                           'held_out': False,
                                                           'license': 'CC '
                                                                      'BY-SA '
                                                                      '4.0'},
    'Nordic_Ware_Original_Bundt_Pan': {   'bounds': [   [   -0.135159,
                                                            -0.13243,
                                                            -0.050374],
                                                        [   0.128712,
                                                            0.131002,
                                                            0.049592]],
                                          'category': 'None',
                                          'held_out': False,
                                          'license': 'CC BY-SA 4.0'},
    'Now_Designs_Bowl_Akita_Black': {   'bounds': [   [   -0.079923,
                                                          -0.078507,
                                                          -0.036604],
                                                      [   0.07976,
                                                          0.080436,
                                                          0.03861]],
                                        'category': 'None',
                                        'held_out': True,
                                        'license': 'CC BY-SA 4.0'},
    'OXO_Soft_Works_Can_Opener_SnapLock': {   'bounds': [   [   -0.0689,
                                                                -0.035187,
                                                                -0.023987],
                                                            [   0.108461,
                                                                0.034539,
                                                                0.032231]],
                                              'category': 'None',
                                              'held_out': False,
                                              'license': 'CC BY-SA 4.0'},
    'Object': {   'bounds': [   [-0.062663, -0.025361, -0.04422],
                                [0.055189, 0.025373, 0.070771]],
                  'category': 'None',
                  'held_out': False,
                  'license': 'CC BY-SA 4.0'},
    'Object_REmvBDJStub': {   'bounds': [   [-0.117459, -0.139706, -0.079155],
                                            [0.118333, 0.144966, 0.171425]],
                              'category': 'None',
                              'held_out': False,
                              'license': 'CC BY-SA 4.0'},
    'Olive_Kids_Birdie_Pack_n_Snack': {   'bounds': [   [   -0.140931,
                                                            -0.129625,
                                                            -0.146342],
                                                        [   0.141042,
                                                            0.116267,
                                                            0.174423]],
                                          'category': 'Bag',
                                          'held_out': False,
                                          'license': 'CC BY-SA 4.0'},
    'Olive_Kids_Dinosaur_Land_Pack_n_Snack': {   'bounds': [   [   -0.140068,
                                                                   -0.124871,
                                                                   -0.145649],
                                                               [   0.147563,
                                                                   0.106111,
                                                                   0.168668]],
                                                 'category': 'Bag',
                                                 'held_out': False,
                                                 'license': 'CC BY-SA 4.0'},
    'Olive_Kids_Dinosaur_Land_Sidekick_Backpack': {   'bounds': [   [   -0.154473,
                                                                        -0.151908,
                                                                        -0.172859],
                                                                    [   0.155654,
                                                                        0.140374,
                                                                        0.207302]],
                                                      'category': 'Bag',
                                                      'held_out': False,
                                                      'license': 'CC BY-SA '
                                                                 '4.0'},
    'Olive_Kids_Game_On_Pack_n_Snack': {   'bounds': [   [   -0.167784,
                                                             -0.125814,
                                                             -0.143169],
                                                         [   0.162159,
                                                             0.128359,
                                                             0.171107]],
                                           'category': 'Bag',
                                           'held_out': False,
                                           'license': 'CC BY-SA 4.0'},
    'Olive_Kids_Mermaids_Pack_n_Snack_Backpack': {   'bounds': [   [   -0.142997,
                                                                       -0.124414,
                                                                       -0.146433],
                                                                   [   0.141969,
                                                                       0.117257,
                                                                       0.174573]],
                                                     'category': 'Bag',
                                                     'held_out': False,
                                                     'license': 'CC BY-SA '
                                                                '4.0'},
    'Orbit_Bubblemint_Mini_Bottle_6_ct': {   'bounds': [   [   -0.110111,
                                                               -0.034672,
                                                               -0.055156],
                                                           [   0.100295,
                                                               0.034905,
                                                               0.064253]],
                                             'category': 'None',
                                             'held_out': False,
                                             'license': 'CC BY-SA 4.0'},
    'Organic_Whey_Protein_Unflavored': {   'bounds': [   [   -0.061069,
                                                             -0.061025,
                                                             -0.082135],
                                                         [   0.0608,
                                                             0.060984,
                                                             0.086928]],
                                           'category': 'Bottles and Cans and '
                                                       'Cups',
                                           'held_out': False,
                                           'license': 'CC BY-SA 4.0'},
    'Organic_Whey_Protein_Vanilla': {   'bounds': [   [   -0.061358,
                                                          -0.060568,
                                                          -0.082246],
                                                      [   0.061223,
                                                          0.060678,
                                                          0.087648]],
                                        'category': 'Bottles and Cans and '
                                                    'Cups',
                                        'held_out': False,
                                        'license': 'CC BY-SA 4.0'},
    'Ortho_Forward_Facing': {   'bounds': [   [   -0.099006,
                                                  -0.106529,
                                                  -0.069553],
                                              [0.103525, 0.128192, 0.120784]],
                                'category': 'None',
                                'held_out': False,
                                'license': 'CC BY-SA 4.0'},
    'Ortho_Forward_Facing_3Q6J2oKJD92': {   'bounds': [   [   -0.083513,
                                                              -0.107254,
                                                              -0.077465],
                                                          [   0.110609,
                                                              0.136456,
                                                              0.118485]],
                                            'category': 'None',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Ortho_Forward_Facing_CkAW6rL25xH': {   'bounds': [   [   -0.126046,
                                                              -0.159996,
                                                              -0.141293],
                                                          [   0.125144,
                                                              0.118805,
                                                              0.124538]],
                                            'category': 'None',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Ortho_Forward_Facing_QCaor9ImJ2G': {   'bounds': [   [   -0.087298,
                                                              -0.089406,
                                                              -0.071108],
                                                          [   0.086079,
                                                              0.090263,
                                                              0.124402]],
                                            'category': 'None',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Pennington_Electric_Pot_Cabana_4': {   'bounds': [   [   -0.052697,
                                                              -0.051666,
                                                              -0.049709],
                                                          [   0.050884,
                                                              0.051767,
                                                              0.048117]],
                                            'category': 'None',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Playmates_Industrial_CoSplinter_Teenage_Mutant_Ninja_Turtle_Action_Figure': {   'bounds': [   [   -0.03749,
                                                                                                       -0.04275,
                                                                                                       -0.057734],
                                                                                                   [   0.045378,
                                                                                                       0.049369,
                                                                                                       0.065979]],
                                                                                     'category': 'Action '
                                                                                                 'Figures',
                                                                                     'held_out': False,
                                                                                     'license': 'CC '
                                                                                                'BY-SA '
                                                                                                '4.0'},
    'RJ_Rabbit_Easter_Basket_Blue': {   'bounds': [   [   -0.099988,
                                                          -0.078716,
                                                          -0.080159],
                                                      [   0.107365,
                                                          0.084858,
                                                          0.155007]],
                                        'category': 'None',
                                        'held_out': False,
                                        'license': 'CC BY-SA 4.0'},
    'Racoon': {   'bounds': [   [-0.082728, -0.118956, -0.073769],
                                [0.069743, 0.196191, 0.137386]],
                  'category': 'None',
                  'held_out': False,
                  'license': 'CC BY-SA 4.0'},
    'Razer_Kraken_71_Chroma_headset_Full_size_Black': {   'bounds': [   [   -0.111356,
                                                                            -0.060571,
                                                                            -0.119945],
                                                                        [   0.113771,
                                                                            0.059374,
                                                                            0.138621]],
                                                          'category': 'Headphones',
                                                          'held_out': False,
                                                          'license': 'CC '
                                                                     'BY-SA '
                                                                     '4.0'},
    'Razer_Kraken_Pro_headset_Full_size_Black': {   'bounds': [   [   -0.09055,
                                                                      -0.048908,
                                                                      -0.160678],
                                                                  [   0.08865,
                                                                      0.087438,
                                                                      0.129508]],
                                                    'category': 'Headphones',
                                                    'held_out': False,
                                                    'license': 'CC BY-SA '
                                                               '4.0'},
    'RedBlack_Nintendo_3DSXL': {   'bounds': [   [   -0.077861,
                                                     -0.067482,
                                                     -0.022266],
                                                 [   0.078116,
                                                     0.066938,
                                                     0.070306]],
                                   'category': 'None',
                                   'held_out': False,
                                   'license': 'CC BY-SA 4.0'},
    'Reebok_CLASSIC_LEGACY_II': {   'bounds': [   [   -0.059462,
                                                      -0.115708,
                                                      -0.069559],
                                                  [   0.071724,
                                                      0.175434,
                                                      0.143254]],
                                    'category': 'Shoe',
                                    'held_out': False,
                                    'license': 'CC BY-SA 4.0'},
    'Reebok_KAMIKAZE_II_MID': {   'bounds': [   [   -0.063927,
                                                    -0.162008,
                                                    -0.055412],
                                                [   0.065166,
                                                    0.131306,
                                                    0.134648]],
                                  'category': 'Shoe',
                                  'held_out': False,
                                  'license': 'CC BY-SA 4.0'},
    'Retail_Leadership_Summit': {   'bounds': [   [   -0.135463,
                                                      -0.142891,
                                                      -0.070072],
                                                  [   0.132002,
                                                      0.145604,
                                                      0.047948]],
                                    'category': 'None',
                                    'held_out': True,
                                    'license': 'CC BY-SA 4.0'},
    'Retail_Leadership_Summit_eCT3zqHYIkX': {   'bounds': [   [   -0.118198,
                                                                  -0.143499,
                                                                  -0.057948],
                                                              [   0.124041,
                                                                  0.130402,
                                                                  0.065722]],
                                                'category': 'None',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'Retail_Leadership_Summit_tQFCizMt6g0': {   'bounds': [   [   -0.125863,
                                                                  -0.138228,
                                                                  -0.062895],
                                                              [   0.121291,
                                                                  0.135307,
                                                                  0.062393]],
                                                'category': 'None',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'Room_Essentials_Bowl_Turquiose': {   'bounds': [   [   -0.079032,
                                                            -0.07918,
                                                            -0.038996],
                                                        [   0.077855,
                                                            0.078041,
                                                            0.04357]],
                                          'category': 'None',
                                          'held_out': False,
                                          'license': 'CC BY-SA 4.0'},
    'Room_Essentials_Fabric_Cube_Lavender': {   'bounds': [   [   -0.133645,
                                                                  -0.146899,
                                                                  -0.111636],
                                                              [   0.146681,
                                                                  0.138847,
                                                                  0.173194]],
                                                'category': 'None',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'Room_Essentials_Kitchen_Towels_16_x_26_2_count': {   'bounds': [   [   -0.074541,
                                                                            -0.087971,
                                                                            -0.034467],
                                                                        [   0.077335,
                                                                            0.095454,
                                                                            0.044025]],
                                                          'category': 'None',
                                                          'held_out': False,
                                                          'license': 'CC '
                                                                     'BY-SA '
                                                                     '4.0'},
    'Room_Essentials_Mug_White_Yellow': {   'bounds': [   [   -0.056924,
                                                              -0.052607,
                                                              -0.05422],
                                                          [   0.079914,
                                                              0.049584,
                                                              0.050574]],
                                            'category': 'None',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Shark': {   'bounds': [   [-0.0774, -0.144089, -0.0627],
                               [0.098442, 0.242973, 0.098513]],
                 'category': 'None',
                 'held_out': False,
                 'license': 'CC BY-SA 4.0'},
    'Smith_Hawken_Woven_BasketTray_Organizer_with_3_Compartments_95_x_9_x_13': {   'bounds': [   [   -0.18876,
                                                                                                     -0.154004,
                                                                                                     -0.090446],
                                                                                                 [   0.171966,
                                                                                                     0.103449,
                                                                                                     0.178283]],
                                                                                   'category': 'None',
                                                                                   'held_out': True,
                                                                                   'license': 'CC '
                                                                                              'BY-SA '
                                                                                              '4.0'},
    'Sonicare_2_Series_Toothbrush_Plaque_Control': {   'bounds': [   [   -0.088328,
                                                                         -0.0513,
                                                                         -0.120262],
                                                                     [   0.088956,
                                                                         0.051979,
                                                                         0.121899]],
                                                       'category': 'None',
                                                       'held_out': True,
                                                       'license': 'CC BY-SA '
                                                                  '4.0'},
    'Sonny_School_Bus': {   'bounds': [   [-0.080177, -0.135247, -0.091248],
                                          [0.082656, 0.104706, 0.139111]],
                            'category': 'None',
                            'held_out': False,
                            'license': 'CC BY-SA 4.0'},
    'Sootheze_Cold_Therapy_Elephant': {   'bounds': [   [   -0.132393,
                                                            -0.115208,
                                                            -0.073659],
                                                        [   0.135539,
                                                            0.105461,
                                                            0.133787]],
                                          'category': 'Stuffed Toys',
                                          'held_out': False,
                                          'license': 'CC BY-SA 4.0'},
    'Sootheze_Toasty_Orca': {   'bounds': [   [   -0.097514,
                                                  -0.171003,
                                                  -0.039468],
                                              [0.116755, 0.236273, 0.105307]],
                                'category': 'Stuffed Toys',
                                'held_out': False,
                                'license': 'CC BY-SA 4.0'},
    'Spritz_Easter_Basket_Plastic_Teal': {   'bounds': [   [   -0.094618,
                                                               -0.094442,
                                                               -0.044794],
                                                           [   0.096672,
                                                               0.088192,
                                                               0.08413]],
                                             'category': 'None',
                                             'held_out': False,
                                             'license': 'CC BY-SA 4.0'},
    'Squirrel': {   'bounds': [   [-0.0509, -0.067375, -0.049742],
                                  [0.048948, 0.073716, 0.081944]],
                    'category': 'None',
                    'held_out': True,
                    'license': 'CC BY-SA 4.0'},
    'Sterilite_Caddy_Blue_Sky_17_58_x_12_58_x_9_14': {   'bounds': [   [   -0.161729,
                                                                           -0.228877,
                                                                           -0.119871],
                                                                       [   0.153979,
                                                                           0.217712,
                                                                           0.114544]],
                                                         'category': 'None',
                                                         'held_out': False,
                                                         'license': 'CC '
                                                                    'BY-SA '
                                                                    '4.0'},
    'Teenage_Mutant_Ninja_Turtles_Rahzar_Action_Figure': {   'bounds': [   [   -0.046361,
                                                                               -0.041838,
                                                                               -0.075665],
                                                                           [   0.024341,
                                                                               0.040512,
                                                                               0.062892]],
                                                             'category': 'Action '
                                                                         'Figures',
                                                             'held_out': False,
                                                             'license': 'CC '
                                                                        'BY-SA '
                                                                        '4.0'},
    'Threshold_Bamboo_Ceramic_Soap_Dish': {   'bounds': [   [   -0.06208,
                                                                -0.048894,
                                                                -0.02347],
                                                            [   0.062578,
                                                                0.04918,
                                                                0.027161]],
                                              'category': 'None',
                                              'held_out': False,
                                              'license': 'CC BY-SA 4.0'},
    'Threshold_Basket_Natural_Finish_Fabric_Liner_Small': {   'bounds': [   [   -0.119407,
                                                                                -0.078622,
                                                                                -0.062801],
                                                                            [   0.119878,
                                                                                0.083572,
                                                                                0.084812]],
                                                              'category': 'None',
                                                              'held_out': False,
                                                              'license': 'CC '
                                                                         'BY-SA '
                                                                         '4.0'},
    'Threshold_Porcelain_Coffee_Mug_All_Over_Bead_White': {   'bounds': [   [   -0.078322,
                                                                                -0.048249,
                                                                                -0.056342],
                                                                            [   0.052418,
                                                                                0.048273,
                                                                                0.058282]],
                                                              'category': 'None',
                                                              'held_out': False,
                                                              'license': 'CC '
                                                                         'BY-SA '
                                                                         '4.0'},
    'Threshold_Porcelain_Pitcher_White': {   'bounds': [   [   -0.088801,
                                                               -0.084429,
                                                               -0.129804],
                                                           [   0.150081,
                                                               0.08437,
                                                               0.148642]],
                                             'category': 'None',
                                             'held_out': False,
                                             'license': 'CC BY-SA 4.0'},
    'Threshold_Porcelain_Teapot_White': {   'bounds': [   [   -0.090422,
                                                              -0.095397,
                                                              -0.05281],
                                                          [   0.096264,
                                                              0.088862,
                                                              0.083535]],
                                            'category': 'None',
                                            'held_out': True,
                                            'license': 'CC BY-SA 4.0'},
    'Threshold_Ramekin_White_Porcelain': {   'bounds': [   [   -0.056515,
                                                               -0.05671,
                                                               -0.028887],
                                                           [   0.05547,
                                                               0.055012,
                                                               0.023879]],
                                             'category': 'None',
                                             'held_out': False,
                                             'license': 'CC BY-SA 4.0'},
    'Top_Paw_Dog_Bow_Bone_Ceramic_13_fl_oz_total': {   'bounds': [   [   -0.094031,
                                                                         -0.093455,
                                                                         -0.032319],
                                                                     [   0.090326,
                                                                         0.092139,
                                                                         0.036154]],
                                                       'category': 'None',
                                                       'held_out': False,
                                                       'license': 'CC BY-SA '
                                                                  '4.0'},
    'Top_Paw_Dog_Bowl_Blue_Paw_Bone_Ceramic_25_fl_oz_total': {   'bounds': [   [   -0.076182,
                                                                                   -0.076486,
                                                                                   -0.021161],
                                                                               [   0.076312,
                                                                                   0.076588,
                                                                                   0.039155]],
                                                                 'category': 'None',
                                                                 'held_out': False,
                                                                 'license': 'CC '
                                                                            'BY-SA '
                                                                            '4.0'},
    'Toys_R_Us_Treat_Dispenser_Smart_Puzzle_Foobler': {   'bounds': [   [   -0.077368,
                                                                            -0.07657,
                                                                            -0.076427],
                                                                        [   0.077354,
                                                                            0.077334,
                                                                            0.077031]],
                                                          'category': 'None',
                                                          'held_out': False,
                                                          'license': 'CC '
                                                                     'BY-SA '
                                                                     '4.0'},
    'Travel_Mate_P_series_Notebook': {   'bounds': [   [   -0.165614,
                                                           -0.173088,
                                                           -0.036832],
                                                       [   0.167061,
                                                           0.202288,
                                                           0.157034]],
                                         'category': 'None',
                                         'held_out': False,
                                         'license': 'CC BY-SA 4.0'},
    'TriStar_Products_PPC_Power_Pressure_Cooker_XL_in_Black': {   'bounds': [   [   -0.157168,
                                                                                    -0.150235,
                                                                                    -0.141481],
                                                                                [   0.154698,
                                                                                    0.143552,
                                                                                    0.188246]],
                                                                  'category': 'None',
                                                                  'held_out': False,
                                                                  'license': 'CC '
                                                                             'BY-SA '
                                                                             '4.0'},
    'UGG_Cambridge_Womens_Black_7': {   'bounds': [   [   -0.09162,
                                                          -0.159024,
                                                          -0.073502],
                                                      [   0.07276,
                                                          0.114868,
                                                          0.142644]],
                                        'category': 'Shoe',
                                        'held_out': False,
                                        'license': 'CC BY-SA 4.0'},
    'UGG_Classic_Tall_Womens_Boots_Grey_7': {   'bounds': [   [   -0.105186,
                                                                  -0.163235,
                                                                  -0.118938],
                                                              [   0.07978,
                                                                  0.118399,
                                                                  0.210965]],
                                                'category': 'Shoe',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'Utana_5_Porcelain_Ramekin_Large': {   'bounds': [   [   -0.066118,
                                                             -0.066388,
                                                             -0.028198],
                                                         [   0.06638,
                                                             0.065451,
                                                             0.0414]],
                                           'category': 'None',
                                           'held_out': False,
                                           'license': 'CC BY-SA 4.0'},
    'Vtech_Roll_Learn_Turtle': {   'bounds': [   [   -0.084315,
                                                     -0.127408,
                                                     -0.053459],
                                                 [   0.085117,
                                                     0.105086,
                                                     0.064054]],
                                   'category': 'None',
                                   'held_out': False,
                                   'license': 'CC BY-SA 4.0'},
    'Weisshai_Great_White_Shark': {   'bounds': [   [   -0.083626,
                                                        -0.076455,
                                                        -0.023032],
                                                    [   0.06007,
                                                        0.090622,
                                                        0.051737]],
                                      'category': 'None',
                                      'held_out': False,
                                      'license': 'CC BY-SA 4.0'},
    'Whey_Protein_Vanilla': {   'bounds': [   [   -0.061171,
                                                  -0.060969,
                                                  -0.082322],
                                              [0.061124, 0.06106, 0.086709]],
                                'category': 'Bottles and Cans and Cups',
                                'held_out': False,
                                'license': 'CC BY-SA 4.0'},
    'Womens_Hikerfish_Boot_in_Black_Leopard_ridcCWsv8rW': {   'bounds': [   [   -0.06283,
                                                                                -0.141271,
                                                                                -0.054178],
                                                                            [   0.052415,
                                                                                0.103066,
                                                                                0.133658]],
                                                              'category': 'Shoe',
                                                              'held_out': False,
                                                              'license': 'CC '
                                                                         'BY-SA '
                                                                         '4.0'}}

GSO_IDS: List[str] = sorted(GSO_ASSETS)
