"""Deterministic GSO choice, with the geometry the HOST needs.

Regenerate with `bash docker/kubric.sh scripts/refresh_gso_ids.py --write`.

The manifest lives in the container, but scenario sampling runs on the host --
where a body stands, how far a distractor must clear it and what its support
surface is are all decided before anything is rendered. An environment map has
no geometry so `_hdri.py` bakes ids alone; a GSO object does, so this bakes its
BOUNDS as well.

Curated: squat and roughly isotropic (longest axis at most 2.6 x the
shortest). A physics dataset needs bodies whose lawful motion a viewer can
predict -- something that topples unexpectedly reads as the violation.

`held_out` marks the assets in Kubric's own 10% test split, kept so a release
can align its held-out clips with objects the community also treats as unseen.
`license` is carried because non-negotiable 7 requires every asset to ship one,
and `validate` enforces it -- recorded when the source is enabled, not at
release.
"""
from __future__ import annotations

from typing import Dict, List

GSO_ASSETS: Dict[str, dict] = {   'Asus_Z97IPLUS_Motherboard_Mini_ITX_LGA1150_Socket': {   'bounds': [   [   -0.115548,
                                                                               -0.049728,
                                                                               -0.094689],
                                                                           [   0.115988,
                                                                               0.049978,
                                                                               0.094921]],
                                                             'category': 'None',
                                                             'held_out': False,
                                                             'license': 'CC '
                                                                        'BY-SA '
                                                                        '4.0'},
    'BIA_Cordon_Bleu_White_Porcelain_Utensil_Holder_900028': {   'bounds': [   [   -0.074464,
                                                                                   -0.073795,
                                                                                   -0.073534],
                                                                               [   0.073106,
                                                                                   0.07496,
                                                                                   0.101661]],
                                                                 'category': 'None',
                                                                 'held_out': False,
                                                                 'license': 'CC '
                                                                            'BY-SA '
                                                                            '4.0'},
    'BlackBlack_Nintendo_3DSXL': {   'bounds': [   [   -0.077625,
                                                       -0.0679,
                                                       -0.021969],
                                                   [   0.077915,
                                                       0.068893,
                                                       0.068554]],
                                     'category': 'None',
                                     'held_out': False,
                                     'license': 'CC BY-SA 4.0'},
    'Black_Decker_CM2035B_12Cup_Thermal_Coffeemaker': {   'bounds': [   [   -0.115312,
                                                                            -0.127929,
                                                                            -0.167789],
                                                                        [   0.111623,
                                                                            0.1957,
                                                                            0.169148]],
                                                          'category': 'None',
                                                          'held_out': False,
                                                          'license': 'CC '
                                                                     'BY-SA '
                                                                     '4.0'},
    'BlueBlack_Nintendo_3DSXL': {   'bounds': [   [   -0.078221,
                                                      -0.066624,
                                                      -0.022236],
                                                  [   0.078378,
                                                      0.067038,
                                                      0.070419]],
                                    'category': 'None',
                                    'held_out': False,
                                    'license': 'CC BY-SA 4.0'},
    'Bradshaw_International_11642_7_Qt_MP_Plastic_Bowl': {   'bounds': [   [   -0.142866,
                                                                               -0.141254,
                                                                               -0.079294],
                                                                           [   0.139748,
                                                                               0.143836,
                                                                               0.07521]],
                                                             'category': 'None',
                                                             'held_out': True,
                                                             'license': 'CC '
                                                                        'BY-SA '
                                                                        '4.0'},
    'Calphalon_Kitchen_Essentials_12_Cast_Iron_Fry_Pan_Black': {   'bounds': [   [   -0.158762,
                                                                                     -0.158482,
                                                                                     -0.073841],
                                                                                 [   0.163593,
                                                                                     0.165146,
                                                                                     0.072398]],
                                                                   'category': 'None',
                                                                   'held_out': False,
                                                                   'license': 'CC '
                                                                              'BY-SA '
                                                                              '4.0'},
    'Closetmaid_Premium_Fabric_Cube_Red': {   'bounds': [   [   -0.175478,
                                                                -0.143088,
                                                                -0.073495],
                                                            [   0.146192,
                                                                0.131877,
                                                                0.21566]],
                                              'category': 'None',
                                              'held_out': False,
                                              'license': 'CC BY-SA 4.0'},
    'Cole_Hardware_Electric_Pot_Cabana_55': {   'bounds': [   [   -0.070876,
                                                                  -0.070768,
                                                                  -0.066465],
                                                              [   0.070792,
                                                                  0.071166,
                                                                  0.063591]],
                                                'category': 'None',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'Curver_Storage_Bin_Black_Small': {   'bounds': [   [   -0.143571,
                                                            -0.096577,
                                                            -0.056336],
                                                        [   0.142293,
                                                            0.096685,
                                                            0.077682]],
                                          'category': 'None',
                                          'held_out': False,
                                          'license': 'CC BY-SA 4.0'},
    'DPC_tropical_Trends_Hat': {   'bounds': [   [   -0.19135,
                                                     -0.199347,
                                                     -0.100244],
                                                 [   0.185016,
                                                     0.204509,
                                                     0.071574]],
                                   'category': 'Hat',
                                   'held_out': False,
                                   'license': 'CC BY-SA 4.0'},
    'Dixie_10_ounce_Bowls_35_ct': {   'bounds': [   [   -0.076146,
                                                        -0.076784,
                                                        -0.036584],
                                                    [   0.076023,
                                                        0.075299,
                                                        0.042817]],
                                      'category': 'None',
                                      'held_out': False,
                                      'license': 'CC BY-SA 4.0'},
    'Dog': {   'bounds': [   [-0.114771, -0.081997, -0.080322],
                             [0.11722, 0.104137, 0.118939]],
               'category': 'None',
               'held_out': False,
               'license': 'CC BY-SA 4.0'},
    'Don_Franciscos_Gourmet_Coffee_Medium_Decaf_100_Colombian_12_oz_340_g': {   'bounds': [   [   -0.051095,
                                                                                                  -0.051846,
                                                                                                  -0.071229],
                                                                                              [   0.051969,
                                                                                                  0.051277,
                                                                                                  0.069812]],
                                                                                'category': 'Bottles '
                                                                                            'and '
                                                                                            'Cans '
                                                                                            'and '
                                                                                            'Cups',
                                                                                'held_out': False,
                                                                                'license': 'CC '
                                                                                           'BY-SA '
                                                                                           '4.0'},
    'Down_To_Earth_Ceramic_Orchid_Pot_Asst_Blue': {   'bounds': [   [   -0.067614,
                                                                        -0.066504,
                                                                        -0.048243],
                                                                    [   0.065111,
                                                                        0.06623,
                                                                        0.071089]],
                                                      'category': 'None',
                                                      'held_out': True,
                                                      'license': 'CC BY-SA '
                                                                 '4.0'},
    'Ecoforms_Plant_Container_GP16AMOCHA': {   'bounds': [   [   -0.082398,
                                                                 -0.082324,
                                                                 -0.077469],
                                                             [   0.080313,
                                                                 0.07925,
                                                                 0.083819]],
                                               'category': 'None',
                                               'held_out': False,
                                               'license': 'CC BY-SA 4.0'},
    'Elephant': {   'bounds': [   [-0.094318, -0.110356, -0.095586],
                                  [0.097111, 0.099539, 0.174962]],
                    'category': 'None',
                    'held_out': False,
                    'license': 'CC BY-SA 4.0'},
    'Embark_Lunch_Cooler_Blue': {   'bounds': [   [   -0.159324,
                                                      -0.099713,
                                                      -0.084798],
                                                  [   0.13625,
                                                      0.101089,
                                                      0.110758]],
                                    'category': 'None',
                                    'held_out': False,
                                    'license': 'CC BY-SA 4.0'},
    'Fisher_price_Classic_Toys_Buzzy_Bee': {   'bounds': [   [   -0.077759,
                                                                 -0.068605,
                                                                 -0.042748],
                                                             [   0.128144,
                                                                 0.066181,
                                                                 0.069175]],
                                               'category': 'None',
                                               'held_out': False,
                                               'license': 'CC BY-SA 4.0'},
    'Full_Circle_Happy_Scraps_Out_Collector_Gray': {   'bounds': [   [   -0.108486,
                                                                         -0.06619,
                                                                         -0.071871],
                                                                     [   0.10456,
                                                                         0.088862,
                                                                         0.071221]],
                                                       'category': 'None',
                                                       'held_out': False,
                                                       'license': 'CC BY-SA '
                                                                  '4.0'},
    'Granimals_20_Wooden_ABC_Blocks_Wagon_85VdSftGsLi': {   'bounds': [   [   -0.015377,
                                                                              -0.015578,
                                                                              -0.015277],
                                                                          [   0.015249,
                                                                              0.015611,
                                                                              0.015186]],
                                                            'category': 'None',
                                                            'held_out': False,
                                                            'license': 'CC '
                                                                       'BY-SA '
                                                                       '4.0'},
    'Great_Dinos_Triceratops_Toy': {   'bounds': [   [   -0.034738,
                                                         -0.022628,
                                                         -0.039786],
                                                     [   0.034733,
                                                         0.023179,
                                                         0.039398]],
                                       'category': 'None',
                                       'held_out': False,
                                       'license': 'CC BY-SA 4.0'},
    'Hefty_Waste_Basket_Decorative_Bronze_85_liter': {   'bounds': [   [   -0.139633,
                                                                           -0.100545,
                                                                           -0.075485],
                                                                       [   0.131053,
                                                                           0.103624,
                                                                           0.224732]],
                                                         'category': 'None',
                                                         'held_out': False,
                                                         'license': 'CC '
                                                                    'BY-SA '
                                                                    '4.0'},
    'INTERNATIONAL_PAPER_Willamette_4_Brown_Bag_500Count': {   'bounds': [   [   -0.133857,
                                                                                 -0.129567,
                                                                                 -0.069263],
                                                                             [   0.136218,
                                                                                 0.127857,
                                                                                 0.070458]],
                                                               'category': 'None',
                                                               'held_out': False,
                                                               'license': 'CC '
                                                                          'BY-SA '
                                                                          '4.0'},
    'Jansport_School_Backpack_Blue_Streak': {   'bounds': [   [   -0.16724,
                                                                  -0.200038,
                                                                  -0.200601],
                                                              [   0.190416,
                                                                  0.169308,
                                                                  0.239547]],
                                                'category': 'Bag',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'LEGO_5887_Dino_Defense_HQ': {   'bounds': [   [   -0.231135,
                                                       -0.179919,
                                                       -0.076976],
                                                   [   0.220582,
                                                       0.167422,
                                                       0.184734]],
                                     'category': 'Legos',
                                     'held_out': False,
                                     'license': 'CC BY-SA 4.0'},
    'Lenovo_Yoga_2_11': {   'bounds': [   [-0.150025, -0.137243, -0.028198],
                                          [0.149527, 0.182678, 0.157209]],
                            'category': 'None',
                            'held_out': False,
                            'license': 'CC BY-SA 4.0'},
    'Logitech_Ultimate_Ears_Boom_Wireless_Speaker_Night_Black': {   'bounds': [   [   -0.053209,
                                                                                      -0.051188,
                                                                                      -0.127245],
                                                                                  [   0.052636,
                                                                                      0.052814,
                                                                                      0.133421]],
                                                                    'category': 'None',
                                                                    'held_out': False,
                                                                    'license': 'CC '
                                                                               'BY-SA '
                                                                               '4.0'},
    'Mad_Gab_Refresh_Card_Game': {   'bounds': [   [   -0.078074,
                                                       -0.077978,
                                                       -0.078223],
                                                   [   0.077792,
                                                       0.078026,
                                                       0.077682]],
                                     'category': 'Board Games',
                                     'held_out': False,
                                     'license': 'CC BY-SA 4.0'},
    'Markings_Letter_Holder': {   'bounds': [   [   -0.046185,
                                                    -0.098285,
                                                    -0.037716],
                                                [   0.053572,
                                                    0.100088,
                                                    0.103278]],
                                  'category': 'None',
                                  'held_out': False,
                                  'license': 'CC BY-SA 4.0'},
    'Mist_Wipe_Warmer': {   'bounds': [   [-0.132034, -0.061567, -0.116525],
                                          [0.132157, 0.066168, 0.116591]],
                            'category': 'None',
                            'held_out': False,
                            'license': 'CC BY-SA 4.0'},
    'Nescafe_16Count_Dolce_Gusto_Cappuccino_Capsules': {   'bounds': [   [   -0.062041,
                                                                             -0.062206,
                                                                             -0.060542],
                                                                         [   0.061741,
                                                                             0.061766,
                                                                             0.062052]],
                                                           'category': 'Consumer '
                                                                       'Goods',
                                                           'held_out': False,
                                                           'license': 'CC '
                                                                      'BY-SA '
                                                                      '4.0'},
    'Nickelodeon_Teenage_Mutant_Ninja_Turtles_Leonardo': {   'bounds': [   [   -0.054513,
                                                                               -0.078888,
                                                                               -0.058258],
                                                                           [   0.029884,
                                                                               0.038389,
                                                                               0.055456]],
                                                             'category': 'Action '
                                                                         'Figures',
                                                             'held_out': False,
                                                             'license': 'CC '
                                                                        'BY-SA '
                                                                        '4.0'},
    'Nikon_1_AW1_w11275mm_Lens_Silver': {   'bounds': [   [   -0.031325,
                                                              -0.031421,
                                                              -0.038961],
                                                          [   0.031505,
                                                              0.031434,
                                                              0.039671]],
                                            'category': 'Camera',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Now_Designs_Bowl_Akita_Black': {   'bounds': [   [   -0.079923,
                                                          -0.078507,
                                                          -0.036604],
                                                      [   0.07976,
                                                          0.080436,
                                                          0.03861]],
                                        'category': 'None',
                                        'held_out': True,
                                        'license': 'CC BY-SA 4.0'},
    'Object_REmvBDJStub': {   'bounds': [   [-0.117459, -0.139706, -0.079155],
                                            [0.118333, 0.144966, 0.171425]],
                              'category': 'None',
                              'held_out': False,
                              'license': 'CC BY-SA 4.0'},
    'Ortho_Forward_Facing_CkAW6rL25xH': {   'bounds': [   [   -0.126046,
                                                              -0.159996,
                                                              -0.141293],
                                                          [   0.125144,
                                                              0.118805,
                                                              0.124538]],
                                            'category': 'None',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'Pennington_Electric_Pot_Cabana_4': {   'bounds': [   [   -0.052697,
                                                              -0.051666,
                                                              -0.049709],
                                                          [   0.050884,
                                                              0.051767,
                                                              0.048117]],
                                            'category': 'None',
                                            'held_out': False,
                                            'license': 'CC BY-SA 4.0'},
    'RJ_Rabbit_Easter_Basket_Blue': {   'bounds': [   [   -0.099988,
                                                          -0.078716,
                                                          -0.080159],
                                                      [   0.107365,
                                                          0.084858,
                                                          0.155007]],
                                        'category': 'None',
                                        'held_out': False,
                                        'license': 'CC BY-SA 4.0'},
    'Racoon': {   'bounds': [   [-0.082728, -0.118956, -0.073769],
                                [0.069743, 0.196191, 0.137386]],
                  'category': 'None',
                  'held_out': False,
                  'license': 'CC BY-SA 4.0'},
    'Razer_Kraken_Pro_headset_Full_size_Black': {   'bounds': [   [   -0.09055,
                                                                      -0.048908,
                                                                      -0.160678],
                                                                  [   0.08865,
                                                                      0.087438,
                                                                      0.129508]],
                                                    'category': 'Headphones',
                                                    'held_out': False,
                                                    'license': 'CC BY-SA '
                                                               '4.0'},
    'RedBlack_Nintendo_3DSXL': {   'bounds': [   [   -0.077861,
                                                     -0.067482,
                                                     -0.022266],
                                                 [   0.078116,
                                                     0.066938,
                                                     0.070306]],
                                   'category': 'None',
                                   'held_out': False,
                                   'license': 'CC BY-SA 4.0'},
    'Retail_Leadership_Summit_tQFCizMt6g0': {   'bounds': [   [   -0.125863,
                                                                  -0.138228,
                                                                  -0.062895],
                                                              [   0.121291,
                                                                  0.135307,
                                                                  0.062393]],
                                                'category': 'None',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'Room_Essentials_Fabric_Cube_Lavender': {   'bounds': [   [   -0.133645,
                                                                  -0.146899,
                                                                  -0.111636],
                                                              [   0.146681,
                                                                  0.138847,
                                                                  0.173194]],
                                                'category': 'None',
                                                'held_out': False,
                                                'license': 'CC BY-SA 4.0'},
    'Shark': {   'bounds': [   [-0.0774, -0.144089, -0.0627],
                               [0.098442, 0.242973, 0.098513]],
                 'category': 'None',
                 'held_out': False,
                 'license': 'CC BY-SA 4.0'},
    'Smith_Hawken_Woven_BasketTray_Organizer_with_3_Compartments_95_x_9_x_13': {   'bounds': [   [   -0.18876,
                                                                                                     -0.154004,
                                                                                                     -0.090446],
                                                                                                 [   0.171966,
                                                                                                     0.103449,
                                                                                                     0.178283]],
                                                                                   'category': 'None',
                                                                                   'held_out': True,
                                                                                   'license': 'CC '
                                                                                              'BY-SA '
                                                                                              '4.0'},
    'Sonicare_2_Series_Toothbrush_Plaque_Control': {   'bounds': [   [   -0.088328,
                                                                         -0.0513,
                                                                         -0.120262],
                                                                     [   0.088956,
                                                                         0.051979,
                                                                         0.121899]],
                                                       'category': 'None',
                                                       'held_out': True,
                                                       'license': 'CC BY-SA '
                                                                  '4.0'},
    'UGG_Cambridge_Womens_Black_7': {   'bounds': [   [   -0.09162,
                                                          -0.159024,
                                                          -0.073502],
                                                      [   0.07276,
                                                          0.114868,
                                                          0.142644]],
                                        'category': 'Shoe',
                                        'held_out': False,
                                        'license': 'CC BY-SA 4.0'}}

GSO_IDS: List[str] = sorted(GSO_ASSETS)
